lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

lab_3/urls.py
 from django.urls import re_path
from .views import index
#url for app

urlpatterns = [
   re_path('', views.index, name='index'),
]

lab_5/urls.py
from django.urls import re_path
from .views import ScheduleList, ScheduleCreate, addfeedback, savefeedback, delete_all
#url for app

urlpatterns = [
    re_path(r'^jadwal/create/$', ScheduleCreate.as_view(), name='jadwal-form'),
    re_path(r'^jadwal/$', ScheduleList.as_view(), name='jadwal-list'),
    re_path(r'^feedback/$', addfeedback , name='feedback-form'),
    re_path(r'^feedback/save/$', savefeedback, name='feedback-save'),
    re_path(r'^jadwal/detelealldatabase/$', delete_all, name='delete-database')
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from lab_1.views import index as index_lab1
from lab_3.views import *


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^riwayatPendidikan/$', riwayatPendidikan, name='riwayatPendidikan'),
    re_path(r'^riwayatOrganisasi/$', riwayatOrganisasi, name='riwayatOrganisasi'),
    re_path(r'^form/', include(('lab_5.urls', 'form'), namespace='form')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab_3/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

class JadwalPribadi(models.Model):
	nama = models.CharField(max_length=200)
	tempat = models.CharField(max_length=200)
	kategori = models.CharField(null = True, blank = True, max_length=150)
	waktu = models.DateTimeField()

	#displaying name object in django admin
	def __str__(self):
		return self.nama

class Feedback(models.Model):
	nama = models.CharField(max_length=200)
	saran = models.TextField()

	def __str__(self):
		return self.nama

lab_5/forms.py
from django import forms
from .models import JadwalPribadi, Feedback

class Add_Project_Form(forms.ModelForm):

    class Meta:
        model = JadwalPribadi
        fields = ['nama', 'tempat', 'kategori', 'waktu',]
   
    err_msg = [
        'Panjang field maksimal 200 karakter',
        'Panjang field maksimal 150 karakter',
        'Masukkan sesuai input yang tertera',
    ]


    nama_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukkan Nama Kegiatan'
    }

    tempat_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukkan Nama Tempat'
    }

    kategori_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukkan Nama Kategori'
    }

    waktu_attrs = {
        'type':'datetime-local',
        'class' : 'form-control'
    }

    nama = forms.CharField(required=True, widget=forms.TextInput(attrs=nama_attrs), error_messages={'max_length':err_msg[0]})
    tempat = forms.CharField(required=True, widget=forms.TextInput(attrs=tempat_attrs), error_messages={'max_length':err_msg[0]})
    kategori = forms.CharField(required=False,widget=forms.TextInput(attrs=kategori_attrs),error_messages={'max_length':err_msg[1]})
    waktu = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs=waktu_attrs),input_formats=['%Y-%m-%dT%H:%M'])

class Add_Feedback_Form(forms.Form):

    class meta:
        model = JadwalPribadi
        fields = ['nama', 'saran']

    nama_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Namamu (inisial juga boleh)',
    }

    saran_attrs = {
        'type': 'text',
        'row' : 4,
        'cols' : 50,
        'class': 'form-control',
        'placeholder':'Masukkan saran',
    }

    nama = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs=nama_attrs))
    saran = forms.CharField(required=True, widget=forms.Textarea(attrs=saran_attrs))

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Aziz Fikri Hudaya' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999, 6, 4) #TODO Implement this, format (Year, Month, Date)
npm = 1708979184 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_3/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'lab3templates.html')

def about(request):
    return render(request, 'about.html')

def riwayatOrganisasi(request):
    return render(request, 'riwayat organisasi.html')

def riwayatPendidikan(request):
    return render(request, 'riwayat pendidikan.html')

lab_5/views.py
from django.shortcuts import reverse, render, redirect
from django.http import HttpResponseRedirect
from .models import JadwalPribadi, Feedback
from .forms import Add_Project_Form, Add_Feedback_Form
from django.views.generic import CreateView, ListView



class ScheduleList(ListView):
    model = JadwalPribadi
    template_name = 'list_form.html'
    context_object_name = 'jadwal'
    queryset = JadwalPribadi.objects.all()

class ScheduleCreate(CreateView):
    model = JadwalPribadi
    form_class = Add_Project_Form
    template_name = 'form_registration.html'

    def get_success_url(self):
        return reverse('form:jadwal-list')
 
def delete_all(request):
	if request.method == "POST":
	    list = JadwalPribadi.objects.all().delete()
	    return redirect('form:jadwal-list')
	else:
		return redirect('form:jadwal-list')

response = {}
def addfeedback(request):

	response['title'] = 'Add Project'
	response['feedback_form'] = Add_Feedback_Form

	html = 'feedback.html'
	return render(request, html, response)

def savefeedback(request):
	form = Add_Feedback_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['nama'] = request.POST['nama']
		response['saran'] = request.POST['saran']
		feedback = Feedback(nama=response['nama'], saran=response['saran'])
		feedback.save()

		return HttpResponseRedirect("/")

	else:

		return HttpResponseRedirect("/")

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lab 1 PPW</title>
	<style>
	img {
		display: block;
		margin-left: auto;
		margin-right: auto;
	}
	</style>
</head>
<body>
	
    <h1 style="text-align:center;">Hello Visitor!</h1>
	<h2 style="text-align:center;">This is My bio</h2>
	<img alt="Foto Aziz" src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-1/p160x160/27749797_1556709127732148_4464822287938127277_n.jpg?_nc_cat=0&amp;oh=e3dc5768a32bd3992e88dbb4b022f242&amp;oe=5BED2112" height = "150" width = "150">
	<pre style="font-size:150%;">Nama 			: {{ name }} </pre>
    <pre style="font-size:150%;">NPM 			: {{ npm }} </pre>
	<pre style="font-size:150%;">Tempat kuliah 		: Universitas Indonesia </pre>
    <pre style="font-size:150%;">Age			: {{ age }} </pre>
	<pre style="font-size:150%;">Hobby			: Roaming around </pre>
	<pre>Description :</pre>
	<pre>
	Saya Aziz. Kuliah di jurusan Ilmu Komputer UI 2017. 
	suka bermain bermain game bangun kota
	suka jalan-jalan tanpa arah </pre>

	
	<h2 style="text-align:center;">And this is my friends bio</h2>
	<img alt="Achir" src= "http://www.about.tarung2017.com/foto/423.jpg" height = "150" width = "200">
	<pre style="font-size:150%;">Nama 			: Muhamad Achir Suci Ramadhan </pre>
	<pre style="font-size:150%;">NPM 			: 1706979354</pre>
	<pre style="font-size:150%;">Tempat kuliah 		: Universitas Indonesia </pre>
	<pre style="font-size:150%;">Hobby			: Jalan kaki tanpa tujuan yang jelas </pre>
	<pre>Description :</pre>
	<pre>
	Saya Ardan. Kuliah di jurusan Ilmu Komputer UI 2017. 
	Hobi tiduran sambil main HP. 
	Kalau lagi malas ya malas, kalau lagi rajin ya rajin. 
	Suka dengar lagu. Kalau ketemu wi-fi suka streaming Youtube. 
	Ini sudah satu paragraf kan? </pre>
	
	
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

lab_3/templates/about.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    Lab PPW - Home
  {% endblock title %}
</head>

<body>
  	{% block content %}
	<div class= "header">
		<div style="padding-top: 115px; padding-bottom: 115px;">
			<p class = "textheader"> About </p>
				<p style = "text-align: center;font-size: 20px; font-family: Calibri ; width: 50%; margin: auto;">
					project ini dibuat untuk memenuhi tugas lab perancangan dan pemograman web (PPW) serta lab ini dibuat untuk teman-teman yang ingin tahu lebih lanjut mengenai saya </br></br></br> Copyright@2018 AFH
				</p>
			</div>
		</div>
	</div>
	{% endblock %}


</body>

lab_3/templates/lab3templates.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    Lab PPW - Home
  {% endblock title %}
</head>

<body>
  {% block content %}

  <div class= "header">
  	<div class= "row" style= "margin-top: 20px; margin-bottom: 20px">
      <div class="col-md-11">
        <p class= "textheader"> TENTANG SAYA </p>
      </div>
      <div class="col-md-1">
        <img src="{% static 'Asset 8.png' %}" alt="logo email" style= "width: 60px; display: block; padding-top: 10px; margin:auto;">
      </div>
    </div>

    <div class= "row">
      <div class="col-md-3" style="padding-bottom: 35px;">
         <img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-1/p160x160/27749797_1556709127732148_4464822287938127277_n.jpg?_nc_cat=0&oh=e3dc5768a32bd3992e88dbb4b022f242&oe=5BED2112" style= "width: 180px;border-radius: 50%;display: block; margin:auto;">
      </div>

      <div class= "col-md-9">
      	<div class="table-responsive">
	        <table class="table" id="tablePerkenalan">
	          <tbody>
	             <tr>
	              <td>Nama</td>
	              <td>: Aziz Fikri Hudaya</td>
	            </tr>      
	            <tr>
	              <td>TTL</td>
	              <td>: Bengkulu, 4 Juni 1999</td>
	            </tr>
	            <tr>
	              <td>Hobi</td>
	              <td>: Roaming Around, Do Nothing</td>
	            </tr>
	            <tr>
	              <td>Domisili</td>
	              <td>: Jakarta</td>
	            </tr>
	          </tbody>
	        </table>
   		</div>
      </div>
    </div>

    <div class= "row">
      <div class="col-md-3">
        <div class="contactperson">
          <img src="{% static 'Asset 1.png' %}" style="display: block; margin:auto;">
        </div>
      </div>
      <div class="col-md-9">
        <p id = "deskripsi">Deskripsi Diri: <br>
          Mahasiswa Fasilkom UI angkatan 2017. Seorang yang menyukai meme dan suka berkeliling tanpa arah. menyukai tantangan serta berusaha untuk menjadi lebih baik.
        </p>
      </div>
    </div>
  </div>

  <div class="row" id = "subutama">
    <div class="col-md-4" id = "bagi3">
      <div class= "row" style = "background-color: #487FFF" >
        <p id = "text">
          Riwayat Pendidikan
        </p>
      </div>
      <div class= "row" id = "row3">
        <p class="text2"><img src= "{% static 'Asset SD.png' %}">
          SDIT IQRA'1 Bengkulu
        </p>
        <p class="text2"><img src= "{% static 'Asset SMP.png' %}">
          SMPIT IQRA Bengkulu
        </p>
        <p class="text2"><img src= "{% static 'Asset SMA.png' %}">
          SMAN 5 Kota Bengkulu
        </p>
        <p class="text2"><img src="{% static 'Asset S1.png' %}">
          Fakultas Ilmu Komputer UI
        </p>
      </div>
        
      <div class= "row" style = "background-color:white;margin-bottom :20px;">
      	<a href="/riwayatPendidikan">
         <p style= "text-align: center;"><img src= "{% static 'Asset.png' %}" > </p>
     	</a>
      </div>
    </div>
    <div class="col-md-4" id = "bagi3">
      <div class= "row" style = "background-color: #FFA82F;">
        <p id = "text">
          Keahlian
        </p>
      </div>
       <div class= "row" id = "row3">
       <p id = "text3"> Python </p>
        <div class="progress" style="margin-left: 30px; margin-right: 30px;">
          <div class="progress-bar" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        
        <p id = "text3"> Java </p>
        <div class="progress" style="margin-left: 30px; margin-right: 30px;">
          <div class="progress-bar" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <p id = "text3"> Desain Grafis </p>
        <div class="progress" style="margin-left: 30px; margin-right: 30px;">
          <div class="progress-bar" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <p id = "text3"> Desain web </p>
        <div class="progress" style="margin-left: 30px; margin-right: 30px;">
           <div class="progress-bar" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <p id = "text3"> HTML </p>
        <div class="progress" style="margin-left: 30px; margin-right: 30px;">
          <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
        </div>


      </div>
      <div class= "row" style = "background-color:white;margin-bottom :20px;">
        <p style= "text-align: center;"><img src= "{% static 'Asset.png' %}"> </p>
      </div>

    </div>



    <div class="col-md-4" id = "bagi3">
      <div class= "row" style = "background-color: #FF7176;">
        <p id = "text">
          Riwayat Organisasi
        </p>
      </div>
        <div class= "row" id = "row3">
          <ul style="list-style-type:bullet; padding-left: 30px">
            <li id="li2">Staff Media FUKI Fasilkom UI</li>
            <li id="li2">Staff Desain BKUI’18</li>

          </ul>  
        </div>
      <div class= "row" style = "background-color:white;margin-bottom :20px;">
        <a href= "/riwayatOrganisasi">
         <p style= "text-align: center;"><img src= "{% static 'Asset.png' %}"> </p>
       </a>
      </div>
  </div>
  {% endblock %}
</body>

</html>

lab_3/templates/riwayat organisasi.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    Lab PPW - Home
  {% endblock title %}
</head>

<body>
  	{% block content %}

	<div class= "header">
		<div style="background-color : #FF7176">
	  		<div class= "row" style= "margin-top: 10px; margin-bottom: 10px">
	  			<p class= "textheadersubpage"> Riwayat Organisasi </p>
	  		</div>
	  		<div class="row">
	  			<img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-1/p160x160/27749797_1556709127732148_4464822287938127277_n.jpg?_nc_cat=0&oh=e3dc5768a32bd3992e88dbb4b022f242&oe=5BED2112" style= "width: 150px;border-radius: 50%;display: block; margin:auto;"> 
	  		</div>
	  		<div class="row">
	  			<p class = "textUnderPhoto"> Aziz Fikri Hudaya </p>
	  		</div>
	  	</div>

	  	<div class = "row" style = "margin-top: 20px; margin-bottom: 20px">
	  		<p class = "judulTable" > Organisasi </p>
	  		<div class="table-responsive">
		  		<table class="table" id = "tableSubPage">
			      	<thead>
			      		<tr>
			      			<th>Tahun</th>
					        <th>Nama Organisasi</th>
					        <th>Jabatan</th>
					    </tr>
			    	</thead>
			   		<tbody>
			      		<tr>
					        <td>2018</td>
					        <td>FUKI Fasilkom UI</td>
					        <td>Staff Media</td>
				     	</tr>
				     	<tr>
					        <td>2018</td>
					        <td>Himamira UI</td>
					        <td>BPH Eksternal</td>
				     	</tr>
				     	<tr>
					        <td>2018</td>
					        <td>TRUI</td>
					        <td>Anggota Muda</td>
				     	</tr>
				    </tbody>
			  </table>
			</div>
		</div>

		<p class = "judulTable" > Kepanitiaan </p>
		<div class="table-responsive">
		  		<table class="table" id = "tableSubPage">
			      	<thead>
			      		<tr>
			      			<th>Tahun</th>
					        <th>Nama Kepanitiaan</th>
					        <th>Jabatan</th>
					    </tr>
			    	</thead>
			   		<tbody>
			      		<tr>
					        <td>2018</td>
					        <td>Bedah Kampus UI</td>
					        <td>Staff Desain</td>
				     	</tr>
				     	<tr>
					        <td>2018</td>
					        <td>UI Goes To Bengkulu</td>
					        <td>Staff HPD </td>
				     	</tr>
				     	<tr>
					        <td>2017</td>
					        <td>OH Fasilkom UI</td>
					        <td>Asisten Lab</td>
				     	</tr>
				    </tbody>
			  </table>
			</div>

	</div>
	{% endblock %}
</body>

lab_5/templates/feedback.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
        	Lab PPW - Form Registration
    	{% endblock title %}
	</title>
</head>

<body>
	{% block content %}
	<div class = 'header' style="padding: 20px;">
  		<div>
  			<a href="{% url 'index' %}" class="btn btn-default" role="button" aria-pressed="true">Kembali</a>
		</div>
		<div>
			<p style="font-size: 24px; margin-top: 10px;">Form Feedback</p>
		</div>
		<div>
			<form class="form" action="{% url 'form:feedback-save' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ feedback_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Masukkan Saran </button>
            </form>
        </div>
    </div>
    {% endblock %}
</body>

lab_5/templates/form_registration.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
        	Lab PPW - Form Registration
    	{% endblock title %}
	</title>
</head>

<body>
	{% block content %}
	
	<div class = 'header' style="padding: 20px;">
  		<div>
  			<a href="/form/jadwal" class="btn btn-default" role="button" aria-pressed="true">Kembali</a>
		</div>
		<div>
			<p class= "textheader"> Form Jadwal Kegiatan </p>
		</div>
		<div>
			<form class="form-block" action="{% url 'form:jadwal-form' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ form }}
                </div>
                <button type="submit" class="btn btn-primary">Input Jadwal Kegiatan</button>
            </form>

		</div>
	</div>
	{% endblock %}
</body>
</html>

lab_5/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  
  <title>
    {% block title %}
        Lab PPW - Home
    {% endblock title %}
  </title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
  <link rel="stylesheet" href= "{%static 'styles.css' %}">


</head>

  <body>

    <header>
      {% include 'layout/navbar.html' %}
    </header>

    <content>
      {% block content %}
       <!-- content goes here -->
      {% endblock content %}
    </content>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </body>
</html>

lab_5/templates/layout/navbar.html
<!DOCTYPE html>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="#">Lab PPW</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/about">About </a></li>
          <li><a href="{% url 'form:feedback-form' %}">Feedback </a></li>
          <li><a href="{% url 'form:jadwal-list' %}">Jadwal</a></li>
        </ul>
      </div>
    </div>
  </nav>
<html>

lab_5/templates/list_form.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html>
<head>
	<title>
		{% block title %}
        	Lab PPW - Form Registration
    	{% endblock title %}
	</title>
</head>

<body>
	{% block content %}
	<div class = 'header' style="padding: 20px;">
		<p class= "textheader">Jadwal Kegiatan </p>

		{% if jadwal%}
			<div class="table-responsive">
		  		<table class="table">
			      	<thead style="background-color: #676767; color: white;">
			      		<tr>
			      			<th>Nama</th>
					        <th>Tempat</th>
					        <th>Kategori</th>
					        <th>Tanggal</th>
					        <th>Waktu</th>
					    </tr>
			    	</thead>

			    	
			   		{% for i in jadwal%}
			   		{% language 'id' %}
			      		<tr>
					        <td> {{i.nama}}</td>
					        <td> {{i.tempat}}</td>
					        <td>
					        	{% if i.kategori %}
					        		{{i.kategori}}
					        	{% else %}
					        		- 
					        	{% endif %}
					        </td>
					        <td>
					        	{{ i.waktu|date:"l, j F Y" }}
					        </td>
					        <td>
					        	{{ i.waktu|date:"g:i A"}}
					        </td>
				     	</tr>
				     {% endlanguage %}
				     {% endfor %}
			  </table>
			</div>
		{% else %}
			<p style="text-align: center;"> tidak ada kegiatan, have a nice day! </p>
		{% endif %}
		
  		<a href= "{% url 'form:jadwal-form' %}" class="btn btn-primary" role="button" aria-pressed="true">Tambah Kegiatan</a>

  		<form class="form" action="{% url 'form:delete-database' %}" method="POST" style="padding-top: 5px">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Hapus semua data</button>
        </form>
		
	</div>
	
	{% endblock %}
</body>
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}